export const CHANNEL_ID = '@lisa_kisa56';

export const BENGAL_STICKER = 'CAACAgIAAxkBAAEQj5docNHqRsBH-lLiM0aYKAoTGYLeFwACGxEAAoTxOUtu3U8V7CcAAdI2BA';
export const BENGAL_STICKER_BEER = 'CAACAgIAAxkBAAEQj5tocNIs-iZOhkYFuryoideMo3zxOQACTxAAAtcFQUsWWxiWQ33i7zYE';
